services:
  - type: web
    name: dental-api
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dental-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: dental-db
    plan: free
    ipAllowList: [] 