services:
  - type: web
    name: dental-api
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma db push --force-reset
      npm run seed
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://admin:5hYJSHwqezzN7guskUPx2Zje20A7I6EN@dpg-ct6be3l6l47c738302pg-a/mydb_pw3y
      - key: NODE_ENV
        value: production

databases:
  - name: dental-db
    plan: free
    ipAllowList: [] 